WRAP_CLASS("itk::GeneralizedDistanceTransformImageFilter" POINTER)
  # the 2nd parameter mus be signed
  WRAP_IMAGE_FILTER_COMBINATIONS("${WRAP_ITK_INT}" "${WRAP_ITK_REAL};${WRAP_ITK_SIGN_INT}")
  WRAP_IMAGE_FILTER_COMBINATIONS("${WRAP_ITK_INT}" "${WRAP_ITK_REAL};${WRAP_ITK_SIGN_INT}" "${WRAP_ITK_COV_VECTOR_REAL}")
END_WRAP_CLASS()
